services:
  postgres-db:
    image: postgres:15-alpine
    container_name: sparta-postgres
    environment:
      POSTGRES_USER: sparta_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sparta_logistics
    ports:
      - "54321:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  redis-cache:
    image: redis:7-alpine
    container_name: sparta-redis
    ports:
      - "6379:6379"

  # ─── 여기 아래부터 우리 애플리케이션 코드를 도커로 연결하는 설정입니다 ───
  
  eureka-server:
    build: ./eureka-server
    container_name: boxoffice-eureka
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: boxoffice-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  user-service:
    build: ./user-service
    container_name: boxoffice-user-service
    ports:
      - "8081:8081"
    env_file:
      - ./user-service/.env # 유저 서비스 내부의 .env 환경변수를 자동으로 도커에 주입
    depends_on:
      - eureka-server
      - postgres-db

volumes:
  postgres_data: