services:
  postgres-db:
    image: postgres:15-alpine
    container_name: sparta-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker_data/postgres:/var/lib/postgresql/data

  redis-cache:
    image: redis:7-alpine
    container_name: sparta-redis
    ports:
      - "6379:6379"

  # ─── 여기 아래부터 우리 애플리케이션 코드를 도커로 연결하는 설정입니다 ───
  
  eureka-server:
    build: ./eureka-server
    container_name: boxoffice-eureka
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: boxoffice-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - eureka-server

  user-service:
    build: ./user-service
    container_name: boxoffice-user-service
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    depends_on:
      - eureka-server
      - postgres-db

  hub-service:
    build: ./hub-service
    container_name: boxoffice-hub-service
    ports:
      - "8083:8083"
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgres-db
    depends_on:
      - eureka-server
      - postgres-db
      - redis-cache

  order-service:
    build: ./order-service
    container_name: boxoffice-order
    ports:
      - "8084:8084"
    env_file:
      - ./.env
    environment:
      - DB_HOST=postgres-db
    depends_on:
      - eureka-server
      - postgres-db
      - redis-cache

  # 6. 배송 담당자 서비스
  delivery-manager-service:
    build: ./delivery-manager-service
    container_name: boxoffice-delivery-manager
    ports:
      - "8086:8086"
    env_file:
      - ./.env
    depends_on:
      - eureka-server
      - postgres-db

  # 7. 배송 서비스
  delivery-service:
    build: ./delivery-service
    container_name: boxoffice-delivery-service
    ports:
      - "8085:8085"
    env_file:
      - ./.env
    depends_on:
      - eureka-server
      - postgres-db

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: boxoffice-keycloak
    command: start-dev
    environment:
#      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
#      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
#      KC_HTTP_PORT: 8080
#      KC_HEALTH_ENABLED: "true"
#      KC_METRICS_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: boxoffice123
      KC_HTTP_RELATIVE_PATH: /
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8089:8080"
    volumes:
      - ./docker_data/keycloak:/opt/keycloak/data
    depends_on:
      - postgres-db