server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**

        - id: deliverymanagerservice
          uri: lb://deliverymanagerservice
          predicates:
            - Path=/api/v1/deliverymanagers/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/