server:
  port: 8081

spring:
  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/boxoffice-realm

  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      okhttp:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:sparta_logistics}?currentSchema=user_schema
    username: ${DB_USERNAME:sparta_admin}
    password: ${DB_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  url: http://localhost:8089
  realm: boxoffice-realm
  admin:
    username: admin
    password: boxoffice123
    client-id: admin-cli

logging:
  level:
    org.springframework.security: TRACE