server:
  port: 8086  #

spring:
  application:
    name: delivery-manager-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/boxoffice-realm

  # 1. (Spring Boot 3.5.x )
  cloud:
    compatibility-verifier:
      enabled: false

  # 2. PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:54321/${DB_NAME:sparta_logistics}?currentSchema=delivery_manager_schema
    username: ${DB_USERNAME:sparta_admin}
    password: ${DB_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 3. Redis
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/