server:
  port: 8761

spring:
  application:
    name: eureka-server

  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    # 개발 환경 빠른 디버깅용 설정. 프로덕션(운영) 배포 시에는 true로 변경 권장!
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000